export const ROOMS_FETCH_REQUESTED = 'ROOMS_FETCH_REQUESTED';
export const ROOMS_FETCH_SUCCEED = 'ROOMS_FETCH_SUCCEED';
export const ROOMS_FETCH_FAILED = 'ROOMS_FETCH_FAILED';
export const ADMIN_CHOOSE_ROOM = 'ADMIN_CHOOSE_ROOM';



export const MESSAGES_FETCH_REQUESTED = 'MESSAGES_FETCH_REQUESTED';
export const MESSAGES_FETCH_SUCCEED = 'MESSAGES_FETCH_SUCCEED';
export const MESSAGES_FETCH_FAILED = 'MESSAGES_FETCH_FAILED';

export const AGENT_INFO_FETCH_REQUESTED = 'AGENT_INFO_FETCH_REQUESTED';
export const AGENT_INFO_FETCH_SUCCEED = 'AGENT_INFO_FETCH_SUCCEED';
export const AGENT_INFO_FETCH_FAILED = 'AGENT_INFO_FETCH_FAILED';
