export const ROOMS_FETCH_REQUESTED = 'ROOMS_FETCH_REQUESTED';
export const ROOMS_FETCH_SUCCEED = 'ROOMS_FETCH_SUCCEED';
export const ROOMS_FETCH_FAILED = 'ROOMS_FETCH_FAILED';
export const ADMIN_CHOOSE_ROOM = 'ADMIN_CHOOSE_ROOM';